DROP DATABASE IF EXISTS CellCultureDB;
CREATE DATABASE CellCultureDB;
USE CellCultureDB;

-- 1. RESEARCHER
CREATE TABLE RESEARCHER (
    ResearcherID INT PRIMARY KEY,
    FirstName VARCHAR(40) NOT NULL,
    LastName VARCHAR(40) NOT NULL,
    EmailAddress VARCHAR(100),
    OfficePhone VARCHAR(20)
);

-- 2. INCUBATOR
CREATE TABLE INCUBATOR (
    IncubatorID INT PRIMARY KEY,
    Model VARCHAR(40) NOT NULL,
    Location VARCHAR(50),
    Temperature FLOAT,
    CO2Percentage FLOAT
);

-- 3. MEDIA
CREATE TABLE MEDIA (
    MediaID INT PRIMARY KEY,
    MediaName VARCHAR(50) NOT NULL,
    SerumType VARCHAR(30),
    BatchNumber VARCHAR(30),
    ExpirationDate DATE
);

-- 4. CELL_LINE
CREATE TABLE CELL_LINE (
    CellLineID INT PRIMARY KEY,
    LineName VARCHAR(50) NOT NULL,
    Organism VARCHAR(40),
    TissueOrigin VARCHAR(50),
    BiosafetyLevel INT
);

-- 5. EXPERIMENT
CREATE TABLE EXPERIMENT (
    ExperimentID INT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    StartDate DATE,
    Status VARCHAR(20),
    CellLineID INT,
    FOREIGN KEY (CellLineID) REFERENCES CELL_LINE(CellLineID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 6. EXPERIMENT_RESEARCHER
CREATE TABLE EXPERIMENT_RESEARCHER (
    ExperimentID INT,
    ResearcherID INT,
    Role VARCHAR(30),
    PRIMARY KEY (ExperimentID, ResearcherID),
    FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ResearcherID) REFERENCES RESEARCHER(ResearcherID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 7. PASSAGE
CREATE TABLE PASSAGE (
    PassageID INT PRIMARY KEY,
    PassageNumber INT NOT NULL,
    PassageDate DATE,
    SplitRatio VARCHAR(10),
    ExperimentID INT,
    MediaID INT,
    IncubatorID INT,
    FOREIGN KEY (ExperimentID) REFERENCES EXPERIMENT(ExperimentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MediaID) REFERENCES MEDIA(MediaID) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (IncubatorID) REFERENCES INCUBATOR(IncubatorID) ON DELETE SET NULL ON UPDATE CASCADE
);

-- 8. CONTAMINATION_TEST
CREATE TABLE CONTAMINATION_TEST (
    TestID INT PRIMARY KEY,
    TestDate DATE,
    ContaminantType VARCHAR(30),
    Result VARCHAR(10),
    PassageID INT,
    FOREIGN KEY (PassageID) REFERENCES PASSAGE(PassageID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 9. CRYOSTOCK
CREATE TABLE CRYOSTOCK (
    StockID INT PRIMARY KEY,
    VialCount INT NOT NULL,
    FreezerLocation VARCHAR(50),
    FreezeDate DATE,
    CellLineID INT,
    FOREIGN KEY (CellLineID) REFERENCES CELL_LINE(CellLineID) ON DELETE CASCADE ON UPDATE CASCADE
);